name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'
      - '.github/workflows/docker-publish.yml'
      - '**/*.sh'
      - '**/*.yaml'
      - '**/*.yml'

permissions:
  contents: read
  packages: write  # Required to push Docker images to GHCR

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

      # Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest